version: "3"
services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose:
      - 9100
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  backend:
    container_name: server
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend/la/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
  
  database:
    image: bitnami/postgresql
    container_name: database
    environment:
      - POSTGRESQL_DATABASE=prohod
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin123
    expose:
      - 5432
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana #в окончательной версии данное поле заполняется более сложным значением
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources